name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Start build notfication
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: html
          message: |
            ⏳ <a href="${{ github.server_url }}/${{ github.repository }}"><b>${{ github.repository }}</b></a>

            ${{ github.workflow }}

            By: ${{ github.actor }}
            Branch: ${{ github.ref }}
            Commit: ${{ github.event.head_commit.message }}
            SHA: ${{ steps.vars.outputs.sha_short }}

            <a href="${{ github.event.head_commit.url }}">Link</a>

      - name: Install tools from asdf config
        uses: ai/asdf-cache-action@v1

      - name: Install dependencies
        run: make install

      - name: Test
        run: make test

      - name: Finish build notfication
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: html
          message: |
            ${{ job.status == 'success' && '✅' || '🆘' }} <a href="${{ github.server_url }}/${{ github.repository }}"><b>${{ github.repository }}</b></a>

            ${{ github.workflow }}

            By: ${{ github.actor }}
            Branch: ${{ github.ref }}
            Commit: ${{ github.event.head_commit.message }}
            SHA: ${{ steps.vars.outputs.sha_short }}

            <a href="${{ github.event.head_commit.url }}">Link</a>
